apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-empty-project-deployment
  namespace: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-empty-project
  template:
    metadata:
      labels:
        app: spring-boot-empty-project
    spec:
      containers:
        - name: spring-boot-empty-project
          image: 192.168.0.111:8050/spring-boot-empty-project
          ports:
            - containerPort: 8877
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-empty-project-service
  namespace: spring-boot
spec:
  selector:
    app: spring-boot-empty-project
  ports:
    - name: http
      port: 8877
      targetPort: 8877
  type: LoadBalancer
