apiVersion: v1
kind: Namespace
metadata:
  name: spring-boot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-boot
  name: spring-boot-rest-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-rest-api
  template:
    metadata:
      labels:
        app: spring-boot-rest-api
    spec:
      containers:
        - name: spring-boot-rest-api
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8876
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest-api-service
  namespace: spring-boot
spec:
  selector:
    app: spring-boot-rest-api
  ports:
    - name: http
      port: 8876
      targetPort: 8876
  type: ClusterIP